biontj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
]

learning_logs/urls.py
"""这里要定义一个learing_logs的url模式"""
# from django.urls import path, include
from django.conf.urls import url
from . import views  # 导入当前文件夹的views文件 也就是learing_logs

# app_name = 'learning_logs'  # 这里还无法理解，2.0的版本需要写上这个才可以定义 learning_logs中url.py的namespace=
urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),  # 路径为空格是为了链接到index.html显示主页。name=将这个url命名为具体的名称，让它在其他地方也可以引用
    # 显示所有的主题
    url(r'^topics/$', views.topics, name='topics'),  # 8000/topics路径链接到topice.html文件
    # # 这里是特定主页的详细界面
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # # 用于添加新主题的网页。
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面，运用主题的id
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 这里需要传递编辑的条目页面的id
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 这是登录页面
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # 这是注销页面
    url(r'^logout/$', views.logout_view, name='logout'),  # 导入的是本目录的views
    # 这是注册页面
    url(r'^register/$', views.register, name='register'),  # 导入的是本目录的views。包含users/register
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)  # 最大输入的字符串
    date_added = models.DateTimeField(auto_now_add=True)  # 自动生成当前日期
    # 用user模型建立一个外键关系模块owner，foreign外建的意思。
    owner = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = '主题'

    def __str__(self):
        """在界面上返回一个简介字符串表示"""
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic)  # foreign外来的意思，起一个继承的意思
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '信息'  # 显示的主题更改为entries

    def __str__(self):
        """返回数据模型的字符串"""
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms  # forms表格的意思
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic  # 这里告诉django根据Topic模型创建表单。
        fields = ['text']  # field 领域  区域为text字段
        labels = {'text': ''}  # labels 标签 这里只是告诉django不要为字段生成标签。


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry  # 这里告诉django根据Entry模型创建表单。
        fields = ['text']  # 要填写的字段
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        # 通过django使用forms.Textarea函数，定制了字段text输入的小部件，将文本区域宽度设置为80，默认是40.cols表示列的意思

# class EntryForm(forms.ModelForm):
#     class Meta:
#         model = Entry
#         fields = ['text']
#         labels = {'text': ''}
#         widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# from .forms import TopicForm

def index(request):
    """这是学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


# Create your views here.
@login_required
def topics(request):
    """显示所有主题的模块"""
    # topics = Topic.objects.order_by("date_added")  # order_by应该是一个排序命令，根据date_added排序
    # 用户登录后request有一个user属性，代码Topic.obj～～user)让django从数据库中获取ower属性为当前用户的Topic对象。
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求是属于当前的用用户。如果不是就引发404错误
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')  # 减号的意思就是降序排列。
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """添加一个新的主题"""
    if request.method != 'POST':
        # 如果没有提交数据：创建一个新的表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理。
        form = TopicForm(request.POST)
        if form.is_valid():  # 检查数据完整
            new_topic = form.save(commit=False)  # 将表单传给new_topic不保存到数据库中。
            new_topic.owner = request.user  # 设置新的主题属性设置为当前的用户
            new_topic.save()  # 然后在添加到数据库中
            # form.save()  # 添加数据到数据库
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):  # topic_id为形参，下面用于获取某一个主题
    """在特定的主题中添加新的条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 如果不是post请求，就建立一个新的清单（entryform实例化）
        form = EntryForm()
    else:
        # POST data submitted; process data,,post提交数据，对数据进行处理。
        form = EntryForm(data=request.POST)  # 通过post数据创建表单
        if form.is_valid():  # 检查数据是否有效
            new_entry = form.save(commit=False)  # 添加数据到表单中，不保存在数据库中，commit提交的意思
            new_entry.topic = topic  # 将new_entry的属性topic设置为从数据库中获得的主题。
            new_entry.save()  # 储存数据
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))  # 重定向到topic视图函数，列表args表示重定向到，新添加的主题。
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑已有的条目"""
    entry = Entry.objects.get(id=entry_id)  # 获取要修改的条目对象，以及相关联的主题，
    topic = entry.topic  #
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 如果是第一次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)  # instance实例的意思，
    else:
        # 以POST提交数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        # 传递实参instance=entry, data=request.POST让django根据，request.post中的数据进行修改。
        if form.is_valid():  # 检查是否有效，
            form.save()  # 储存在数据库中
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm  # 导入了用户创建的表单


def logout_view(request):
    """注销用户视图函数，执行完后返回主页"""
    logout(request)  # 内置函数，直接注销用户
    # 返回主页
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册新的用户"""
    if request.method != 'POST':
        # 如果不是post方式请求，则创建一个新的用户表单。
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():  # 如果数据有效，包含非法字符，密码是否相同，恶意的事情
            # 调用表单中的方法save()，将用户名和密码以散列值保存到数据库中，并返回新创建的用户对象，将它储存到new_user中
            new_user = form.save()
            # 让用户自动登录，再重定向到主页,应该是都这么写的。
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base(副本).html
<p>
    <a href="{% url 'learning_logs:index' %}">学习主页</a> -{# 这里的链接是返回到index.html的链接。 #}
    <a href="{% url 'learning_logs:topics' %}">主题</a> - {# 这里返回的是主题信息。 #}
    {# 在身份验证系统中，每个user都有一个变量is_authenticated属性，如果用户登录该属性为True，否则为False #}
    {% if user.is_authenticated %}
        {# 这里显示一条问候语，提示用户已经登录 #}
        你好：{{ user.username }}.
        {# 这里表示链接到退出登录的视图 #}

        <a href="{% url 'users:logout' %}">退出登录</a>
    {% else %}
        {# 显示一个到登录页面的链接，和注册用户的链接 #}
        <a href="{% url 'users:register' %}">register:注册用户</a> -
        <a href="{% url 'users:login' %}">登录</a>
    {% endif %}
</p>

{# block为块的意思#}
<p>这里是父模板的内容，写在占位符的外面的内容</p>

{% block content %} {% endblock content %}  {# 这里只是一个站位符，其中的信息都将由子模板内容填充 #}
{% block conten %} {% endblock conten %}  {# 占位符是相匹配的，其中的信息都将由子模板内容填充 #}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习笔记</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">我的主题</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>你好：{{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                    <li><a href="{% url 'users:login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <div class="page-header">
        {% block header %}{% endblock %}
    </div>
    <div>
        {% block content %}{% endblock %}
    </div>
</div> <!-- /container -->
</body>
</html>

learning_logs/templates/learning_logs/edit_entry(副本).html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>编辑内容</p>
{#      函数action将表单发回至edit_entry视图函数进行处理，将条目id设置为一个实参，让视图函数能够修改正确的条目对象。#}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">保存</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>编辑内容</p>
{#      函数action将表单发回至edit_entry视图函数进行处理，将条目id设置为一个实参，让视图函数能够修改正确的条目对象。#}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">保存</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index(副本).html
{#子模板的内容都是在父模板的基础上修改的内容。#}

{% extends "learning_logs/base.html" %}
{% block content %}  {# content为整个页面的意思.#}
<p>保持学习的态度的（这里插入的是子模板的内容）</p>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
      <h1>建立你的学习笔记</h1>
  </div>
{% endblock %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">注册一个账户</a> 制作你自己的学习日志，列出你正在学习的主题。
  </h2>
  <h2>
    无论什么时候，只要你学习了一个新的话题，就把你所学到的东西总结出来。
  </h2>
{% endblock %}

learning_logs/templates/learning_logs/new_entry(副本).html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>新的内容</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>  {# 让识图函数关联到正确的主题 #}
    {% csrf_token %}  {# 防止攻击 #}
    {{ form.as_p }}   {# 显示表单，以段落形式渲染所有表单元素 #}
    <button name='submit'>添加内容</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>新的内容</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>  {# 让识图函数关联到正确的主题 #}
    {% csrf_token %}  {# 防止攻击 #}
    {{ form.as_p }}   {# 显示表单，以段落形式渲染所有表单元素 #}
    <button name='submit'>添加内容</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic(副本).html
{#这里显示的是用户的填写表单的界面#}
{% extends "learning_logs/base.html" %}
{% block content %}
    <p>添加新的主题</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {#        添加django中自带的防止攻击命令#}
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">添加主题</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>添加一个新的主题</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method='post'
      class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">添加主题</button>
    {% endbuttons %}

  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic(副本).html
{#这个页面显示的是主题的具体内容#}

{% extends "learning_logs/base.html" %}

{% block content %}
    <p>主题：{{ topic }}</p>
    <p>内容</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新的内容</a>
    </p>
    <ul>
        {% for entry in entries %} {# 遍历全部的entries，都存储在字典centext中。 #}
            <li>
                <p>{{ entry.date_added|date:'M d, Y H:i' }}</p> {# 竖线“|”表示过滤器，以月日，年 时间表示时间戳 #}
                <p>{{ entry.text|linebreaks }}</p> {# 这里表示显示text完整的值。 #}
                <p>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">更改内容</a>
                </p>
            </li>
        {% empty %}
            <li>
                没有记录
            </li>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h2>主题：{{ topic }}</h2>
{% endblock header %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新的内容</a>
    </p>
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                            更改内容</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% empty %}
        <li>
            没有记录
        </li>
    {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics(副本).html
    {#这个页面是显示的全部的主题#}

{# 这是一个子模板 #}
{% extends 'learning_logs/base.html' %}
{% block conten %}
    <p>主题</p>
    <ul>
        {% for topic in topics %}  {# 这里的topics是通过views.py中访问数据库的Topic数据生成遍历的。#}
            <li>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </li>  {# 在模板中打印变量要用双括号 #}
        {% empty %}  {# 如果为空则执行下面的<li> 中的信息。 #}
            <li>没有主题添加</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">添加主题</a>
{% endblock conten %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
  <h1>主题</h1>
{% endblock %}
{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>
    {% empty %}
      <li>没有主题添加</li>
    {% endfor %}
  </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">添加新的主题</a></h3>
{% endblock content %}

users/templates/users/login(副本).html
{% extends "learning_logs/base.html" %}  {# 还是用的学习那边的公板，说明不同应用之间是可以继承另一个应用程序的模板 #}

{% block content %}

  {% if form.errors %}  {# 如果没有在表单form中找到匹配的，提示错误 #}
  <p>用户名或密码错误</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">  {# 设置form表单的url为登录页面的列表 #}
  {% csrf_token %}  {#  #}
  {{ form.as_p }}  {# 将表单form按段落显示 #}

  <button name="submit">登录</button>
      {# 这里包含一个隐藏的表单元素-next（这里严重不懂。。）；value告诉django用户登录成功后将页面定向到主页 #}
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>登录你的账户</h2>
{% endblock %}
{% block content %}
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">登录</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}

users/templates/users/register(副本).html
{% extends "learning_logs/base.html" %}

{% block content %}

    {# form块整个都是一个链接，网页链接到本地users/url中的register,然后转到views视图中的register. #}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">注册</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

    {# form块整个都是一个链接，网页链接到本地users/url中的register,然后转到views视图中的register. #}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">注册</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}